all: start_game

start_game:
	gcc -o tetris gui/cli/gui.c brick_game/tetris/s21_tetris.c -lncurses
	./tetris
clean:
	rm -f tetris

# test:

# gcov_report:
	
# install:

# uninstall:

# dvi:

# dist:

.PHONY: all start_game clean